lab10/app/todo/models.py
from app import db


class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.String(255))
    complete = db.Column(db.Boolean)

lab10/app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class ToDoForm(FlaskForm):
    todo = StringField("Enter a task here", validators=[DataRequired(), Length(min=1, max=50)])
    description = StringField("Enter a description here", validators=[DataRequired(), Length(min=1, max=255)])
    submit = SubmitField("Save")

lab10/app/todo/__init__.py
from flask import Blueprint

todo_bp = Blueprint("todo_bp", __name__, template_folder="templates/todo")

from . import views

lab10/app/todo/views.py
from . import todo_bp
from flask import render_template, redirect, url_for, flash
from app import db
from .models import Todo
from .forms import ToDoForm


@todo_bp.route('/todo', methods=['GET', 'POST'])
def todo():
    form = ToDoForm()
    todo_list = db.session.query(Todo).all()
    if form.validate_on_submit():
        return redirect(url_for("todo_bp.todo"))
    return render_template("todo.html", form=form, todo_list=todo_list)


@todo_bp.route("/add", methods=['GET', 'POST'])
def add():
    form = ToDoForm()
    todo_list = Todo.query.all()
    if form.validate_on_submit():
        new_task = Todo(title=form.todo.data, description=form.description.data, complete=False)
        db.session.add(new_task)
        db.session.commit()
        flash("The new task was added successfully.", "success")
        return redirect(url_for("todo_bp.todo"))
    flash("The new task was not added!", "danger")
    return render_template('todo.html', form=form, todo_list=todo_list)


@todo_bp.route("/update/<int:id>")
def update(id):
    todo = Todo.query.get_or_404(id)
    todo.complete = not todo.complete
    db.session.commit()
    flash(f"The task №{id} was updated.", "success")
    return redirect(url_for("todo_bp.todo"))


@todo_bp.route("/delete/<int:id>")
def delete(id):
    todo = Todo.query.get_or_404(id)
    db.session.delete(todo)
    db.session.commit()
    flash(f"Task №{id} was deleted.", "success")
    return redirect(url_for("todo_bp.todo"))

lab10/app/todo/templates/todo/todo.html
{% extends "base.html" %}
{% block title %}To do{% endblock %}
{% from "render_field.html" import render_field %}
{%block content%}
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-left h-100">
        <div class="col col-lg-9 col-xl-7">
            <div class="card rounded-3">
                <div class="bg-dark-subtle card-body p-4">

                    <h4 class="text-center my-3 pb-3">Python Flask Simple To Do - SQLAlchemy</h4>
                    <form method="post" action="{{url_for('todo_bp.add')}}" class="mb-5 text-center" novalidate>
                        {{ form.csrf_token }}
                        {{ render_field(form.todo) }}
                        {{ render_field(form.description) }}
                        {{ form.submit(class="btn btn-primary btn-lg btn-block") }}
                    </form>

                    <table class="table mb-4">
                        <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Todo item</th>
                            <th scope="col">Description</th>
                            <th scope="col">Status</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for todo in todo_list %}
                        <tr>
                            <th scope="row">{{ todo.id }}</th>
                            <td>{{ todo.title }}</td>
                            <td>{{ todo.description }}</td>
                            <td>
                                {% if todo.complete == False %}
                                <div class="alert alert-secondary" role="alert">In progress</div>
                                {% else %}
                                <div class="alert alert-success" role="alert">Completed</div>
                                {% endif %}
                            </td>
                            <td>
                                <a class="btn btn-success" href="{{url_for('todo_bp.update', id=todo.id)}}">Update</a>
                                <a class="btn btn-danger ms-1" href="{{url_for('todo_bp.delete', id=todo.id)}}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}