lab10/app/cookies/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField("Old password", validators=[DataRequired(), Length(min=4, max=10)])
    new_password = PasswordField("New password", validators=[DataRequired(), Length(min=4, max=10)])
    confirm_password = PasswordField("Confirm new password", validators=[DataRequired(),
                                                                         Length(min=4, max=10),
                                                                         EqualTo('new_password')])
    submit = SubmitField("Submit")

lab10/app/cookies/__init__.py
from flask import Blueprint

cookies = Blueprint("cookies", __name__, template_folder="templates/cookies")

from . import views

lab10/app/cookies/views.py
from . import cookies
from flask import request, render_template, redirect, url_for, make_response, session, flash
from .forms import ChangePasswordForm
from flask_login import current_user, login_required
import json


def add_file_data():
    try:
        with open('app/file.json', 'r') as file:
            d = json.load(file)
        return d
    except FileNotFoundError:
        return flash("File doesn't exist!")


@cookies.route('/info')
@login_required
def info():
    form = ChangePasswordForm()
    username = current_user.username
    return render_template('info.html', form=form, username=username, cookies=request.cookies)


@cookies.route('/add_cookie', methods=['POST'])
def add_cookie():
    form = ChangePasswordForm()
    cookies = request.cookies
    key = request.form.get('key')
    value = request.form.get('value')
    max_age = int(request.form.get('max_age'))
    resp = make_response(render_template('info.html', username=current_user.username, cookies=cookies, form=form))
    resp.set_cookie(key, value, max_age=max_age)
    flash("Cookie is added! Please, refresh the page.", "success")
    return resp


@cookies.route('/remove_cookie', methods=['POST'])
def remove_cookie():
    form = ChangePasswordForm()
    cookies = request.cookies
    key = request.form.get('key')
    resp = make_response(render_template('info.html', username=current_user.username, cookies=cookies, form=form))
    if key in cookies:
        resp.delete_cookie(key)
        flash("Cookie is deleted! Please, refresh the page.", "success")
    return resp


@cookies.route('/remove_all_cookies', methods=['POST'])
def remove_all_cookies():
    form = ChangePasswordForm()
    cookies = request.cookies
    resp = make_response(render_template('info.html', username=current_user.username, cookies=cookies, form=form))
    for key in cookies.keys():
        print(key)
        if key != 'session':
            resp.delete_cookie(key)
    flash("All cookies are deleted!", "success")
    return resp


@cookies.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        old_password = form.old_password.data
        new_password = form.new_password.data
        confirm_password = form.confirm_password.data
        file_data = add_file_data()
        try:
            json_password = file_data['password']
        except TypeError:
            flash("Error with data!", "error")
            raise SystemExit("Error with data!")
        if old_password == json_password:
            if new_password == confirm_password:
                session['password'] = new_password
                with open('app/file.json', "w") as file:
                    file_data['password'] = new_password
                    json.dump(file_data, file)
                    flash("Password was changed.", "success")
                    return redirect(url_for('cookies.info'))
        flash("Password was not changed.", "danger")
        return redirect(url_for('cookies.info'))
    return render_template('info.html', form=form)

lab10/app/cookies/templates/cookies/info.html
{% extends 'base.html' %}
{% block title %}Info{% endblock %}
{% from "render_field.html" import render_field %}
{% block content %}
<h2 class="fs-1 mt-5 text-center">Hello, {{username}}!</h2>
<div class="p-2 mt-4 text-center">
    <p>You've logged in.</p>
    <p>Hi man!</p>
</div>

{% if done %}<p>{{ done }}</p>{% endif %}

<div class="bg-dark-subtle p-5 mt-5 mb-5 text-center">
    <form action={{url_for('cookies.add_cookie')}} method="post">
        <label for="key">Key:</label>
        <input type="text" name="key" id="key">
        <label for="value">Value:</label>
        <input type="text" name="value" id="value">
        <label for="max_age">Max age (sec):</label>
        <input type="number" name="max_age" id="max_age"><br><br>
        <button type="submit" class="btn btn-primary btn-lg">Add Cookie</button>
    </form>
</div>

<div class="bg-dark-subtle p-5 mt-5 mb-5 text-center">
    <form action={{url_for('cookies.remove_cookie')}} method="post">
        <label for="key">Key to delete:</label>
        <input type="text" name="key" id="delete_key"><br><br>
        <button type="submit" class="btn btn-primary btn-lg">Delete Cookie</button>
    </form><br>

    <form action={{url_for('cookies.remove_all_cookies')}} method="post">
        <button type="submit" class="btn btn-primary btn-lg">Delete All</button>
    </form>
</div>

{% if cookies %}
<table class="text-center">
    <tr>
        <th>Key</th>
        <th>Value</th>
    </tr>
    {% for key, value in cookies.items() %}
    <tr>
        <td>{{ key }}</td>
        <td>{{ value }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

<div class="bg-dark-subtle p-5 mt-5 mb-5 text-center">
    <form action={{url_for("cookies.change_password")}} method="post" class="bg-dark-subtle text-center" novalidate>
        {{form.csrf_token}}
        {{render_field(form.old_password)}}
        {{render_field(form.new_password)}}
        {{render_field(form.confirm_password)}}
        {{form.submit(class="btn btn-primary btn-lg")}}
    </form>
</div>
{% endblock %}